sudo: true

env:
# stable
- CHANNEL=stable RELEASE=835.9.0
# beta
- CHANNEL=beta RELEASE=877.1.0
# alpha
- CHANNEL=alpha RELEASE=891.0.0

services:
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_4f0c85a4159b_key -iv $encrypted_4f0c85a4159b_iv -in key.enc -out .travis/key -d
- bash .travis/travis.sh

install:
- docker build -t waltermeyer/pfring-coreos .

script:
- docker run --name build_env -e release=$RELEASE waltermeyer/pfring-coreos

after_success:	
- eval "$(ssh-agent -s)"
- chmod 600 .travis/key
- ssh-add .travis/key
- git remote add deploy git@github.com:waltermeyer/pfring-coreos.git
- docker cp build_env:/builds/ .
- git add builds/
- git commit -m "Travis-CI auto-build for CoreOS $CHANNEL $RELEASE [ci skip]"
- git tag -d $RELEASE
- git push --delete deploy $RELEASE
- git tag $RELEASE -m "Travis-CI auto-build for CoreOS $CHANNEL $RELEASE [ci skip]"
- git push deploy $RELEASE
