sudo: false

env:
# stable
- RELEASE=835.9.0
# beta
- RELEASE=877.1.0
# alpha
- RELEASE=891.0.0

services:
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_4f0c85a4159b_key -iv $encrypted_4f0c85a4159b_iv -in key.enc -out .travis/key -d
- docker build -t waltermeyer/pfring-coreos .

script:
- docker run --name build_env -e release=$RELEASE waltermeyer/pfring-coreos

after_success:	
- eval "$(ssh-agent -s)"
- chmod 600 .travis/key
- ssh-add .travis/key
- git remote add deploy git@github.com:waltermeyer/pfring-coreos.git
- docker cp build_env:/builds/ .
- ls builds/
- ls builds/kernel/
- git add builds/
- git commit -m "Travis-CI auto-build for CoreOS $RELEASE"
- git tag $RELEASE
- git push deploy $RELEASE
